### ISSUE TITLE
Re-Enable HTTP?

### ISSUE THREAD

**Issue by davolesh** [dlandon/zoneminder#17]
With the latest update http access was removed and only https is allowed. Any way to allow http to be enabled as a settings option?

I use zoneminder with Home Assistant using http and with the latest update of zoneminder I cannot get https to work with Home Assistant. The removing of http essentially broke its' intergration ability with Home Assistant. The self-signed certificate cannot be verified by Home Assistant and therefore it cannot be set up.Thanks

**Comment by larizzo** [comment]
@davolesh you can set these two values in home assistant and it should work:

ssl: true
verify_ssl: false

**Comment by davolesh** [comment]
With those settings set, the component loads but the cameras get this error:

Error getting new camera image: Cannot connect to host 192.168.1.10:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)]

**Comment by larizzo** [comment]
@dlandon There's a few people with this "issue" [Reddit](https://www.reddit.com/r/homeassistant/comments/a8bcag/zoneminder_wont_allow_me_to_stream_my_cameras). You could maybe implement it in a different way that you could toggle on or off. I'm not affected as I have a real SSL cert.

**Comment by drock1985** [comment]
Hi,

I would also like to have http acccess re-enabaled. I've been trying do configure Zoneminder with HA as well; including the verify ssl to false (in fact; i'm the user that larizzo has linked to on Reddit). Only way around the camera streaming is to enable http access. The self-signed cert I think is the issue with the current docker build (server is localhost?) but I could be mistaken.

**Comment by dlandon** [comment]
I understand that it would be a simple fix for your issue for me to just re-enable http access, but with all the hacking on the internet happening, security is more important than ever.  I am not inclined to re-enable http access or offer a "work around".  We need to work through this. 

It seems your best option is to get a real security certificate.  You can get a free one from Let's Encrypt.  Your certificate goes in the keys/ folder of Zoneminder and the docker will handle it from there.

Once you have a certificate, set your certificate FQDN name in the keys/ServerName file so Apache will match the certificate.

I saw in reddit the suggestions to hack the docker try to get around the http access block.  It would be less work and more secure to just get an appropriate security certificate and do it right.

**Comment by dlandon** [comment]
The certificate is for Zoneminder and all you should have to do is install it there.

Rename the fullchain.pem to cert.crt.  Rename privkey.pem to cert.key.  Copy these files to the keys/ folder.  They will overwrite the default certificate.  Modify the ServerName file contents from localhost to your FQDN.  Restart the docker and your certificate should be working.

**Comment by drock1985** [comment]
Hi again @dlandon ,

Thanks for helping dlandon. I'm close, but still getting an error when trying to stream when using a proper SSL Cert (copied the one i'm using for my hassio install). I then edited the ServerName file in notepad and changed localhost to 'xxxxxx.duckdns.org' and saved it and rebooted zoneminder. Also rebooted HA after just to make sure. 

I'm getting this error in the logs when trying to view the stream; something about he ssl cert being unable to be verified (even with verify_ssl off in HA) and have this:

2018-12-24 09:29:24 ERROR (MainThread) [homeassistant.core] Error doing job: SSL handshake failed on verifying the certificate
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 609, in uvloop.loop.UVStream._on_eof
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.6/ssl.py", line 694, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/local/lib/python3.6/site-packages/idna_ssl.py", line 19, in patched_match_hostname
    return real_match_hostname(cert, hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 331, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname '192.168.86.129' doesn't match 'xxxxx.duckdns.org'
2018-12-24 09:29:24 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error on transport TCPTransport
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 827, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 171, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.6/ssl.py", line 694, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/local/lib/python3.6/site-packages/idna_ssl.py", line 19, in patched_match_hostname
    return real_match_hostname(cert, hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 331, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname '192.168.86.129' doesn't match 'xxxxx.duckdns.org'

When visiting the zoneminder URL now i'm getting the proper certificate info, so i'm in the right direction but not sure how to get over the last hurdle.

Thanks again.

**Comment by davolesh** [comment]
I got it to work!!! Here's how:
1. Use the DuckDNS add-on in Hass.io and once it's setup, there will be two files in "\\HASSIO\ssl" privkey.pem and fullchain.pem.
2. In "\\HASSIO\ssl" rename "privkey.pem" to "cert.key" and "fullchain.pem" to "cert.crt." Copy these two new files to "\\UNRAIDSERVER\appdata\Zoneminder\keys."
3. In Home Assistant zoneminder component,
zoneminder:
  host: xxxxx.duckdns.org:443/zm
  username: !secret zm_username
  password: !secret zm_password
  ssl: true
  verify_ssl: false

@drock1985 Change your host ip for Zoneminder in Home Assistant t to your DuckDNS domain.

Thanks all for your help!!

**Comment by drock1985** [comment]
hi @davolesh 

I kind of figured that would work but doesn't that open up more security holes now? Now it has to be external connection to even work. Could be wrong on that one. I'll give it a try and see what happens. Thanks.

**Comment by larizzo** [comment]
I'm hitting another issue since switching zoneminder to https with Home-Assistant [Home-Assistant High CPU](https://community.home-assistant.io/t/high-cpu-usage-with-zoneminder-plugin/30418)
Now I'm thinking might be a better idea to have a way to enable the port 80. Maybe a variable that can set the port enabled? I understand the logic of not wanting port 80 exposed but I mean people would have to actually open port 80 externally on their firewalls.

**Comment by dlandon** [comment]
I do appreciate that you want a quick solution to your issue, but I am not comfortable allowing http access any longer.  Users don't necessarily know anything about port forwarding and security when forwarding ports.  https access will at least push them to security if they allow remote access and they don't know what they are doing.

You are not the only person using Zoneminder and I have to be concerned with all users.  The ZmNinja app is pushing more towards https access and valid certificates.  All apps will be moving to more security.  Even security on a LAN is becoming important.

Why don't you present this to Home Assistant for them to solve.  Seems to be more appropriate for them to be be able to handle https access and work out the issues.  It will come up again for them I'm sure.

**Comment by larizzo** [comment]
I don't agree that putting port 80 makes them any safer, forcing a non default password would probably be much safer. The odds that someone is able to sniff your port 80 traffic is rare and would be pretty difficult. Either way this is your build and you can manage it as you see, and I do appreciate the work.

**Comment by dlandon** [comment]
Why do you feel you need a reverse proxy?

I have ownCloud and Zoneminder on my server and use port mapping in my router to direct the traffic:
- External port 443 -> internal port ip1:443 for ownCoud
- External port 8443 -> internal port ip2:443 for Zoneminder
ownCloud and Zoneminder each have their own ip address.  ownCloud and Zoneminder each have a copy of my certificate.

You have several options here:
- Look at my suggestion.
- Find another Zoneminder Docker to do what you want.  Try the official Docker.
- Build your own Docker.

**Comment by dlandon** [comment]
For http access:
- Download the latest docker.
- Do a port mapping 8080->80 tcp

Access will be http:\\ip:8080\zm

I will offer no support for this.

**Comment by sgofferj** [comment]
I'd like to come back to this issue because I'm having it for similar reasons as @cTurtle98. It's common practice to run (micro-) services behind a reverse proxy. Reasons are among others, having a centralized point for certificates, reducing port forwarding complexity, simplifying access (servicea.domain.com/serviceb.domain.com vs. server.domain.com:8080/server.domain.com:8443), better security through centralized access rules, load balancing, etc. etc.
In this scenario, an additional internal SSL path with the need to manually deal with certificates adds a pretty big layer of complexity.
Security is not affected by this because the zm container wouldn't expose any ports on host level but only towards the reverse proxy/edge router inside the container network.

**Comment by dlandon** [comment]
Read the previous comment posted by me.
